# Generated by Django 3.1.2 on 2020-10-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='b_writer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='usage_flag',
            field=models.CharField(default='1', max_length=10, null=True),
        ),
    ]
