# Generated by Django 3.1.2 on 2020-12-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('b_no', models.AutoField(primary_key=True, serialize=False)),
                ('b_title', models.CharField(max_length=255)),
                ('b_note', models.TextField(help_text='내용을 입력하세요.', null=True)),
                ('b_writer', models.CharField(max_length=50, null=True)),
                ('parent_no', models.IntegerField(default=0, null=True)),
                ('b_count', models.PositiveIntegerField(default=0)),
                ('b_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_flag', models.CharField(default='1', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_writer', models.CharField(max_length=50, null=True)),
                ('c_note', models.TextField(help_text='내용을 입력하세요.', null=True)),
                ('c_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardapi.board')),
            ],
        ),
    ]
