# Generated by Django 3.1.2 on 2021-01-06 11:01

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='c_writer',
            field=models.CharField(max_length=50, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
