# Generated by Django 3.1.2 on 2021-01-06 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardapi', '0002_auto_20210106_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='boardapi.board'),
        ),
    ]
