# Generated by Django 3.1.2 on 2021-07-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapi', '0003_auto_20210106_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pw1', models.CharField(max_length=10)),
                ('pw2', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='b_note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='c_note',
            field=models.TextField(null=True),
        ),
    ]
