# Generated by Django 3.1.2 on 2020-12-07 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_writer', models.CharField(max_length=50, null=True)),
                ('c_note', models.TextField(help_text='내용을 입력하세요.', null=True)),
                ('c_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
        ),
    ]
